### ISSUE TITLE
Console Control Hitboxes move when right-clicked

### ISSUE THREAD

**Issue by Swift2337** [Jeryn99/TardisRefined#93]
### Issue description

The console controls' hitboxes are moving relative to the angle the hitbox was right-clicked.

https://user-images.githubusercontent.com/18432938/220212015-11712597-c154-4338-8324-08710e7cac31.mp4

### Steps to reproduce

This problem arose after an attempt to get the controls working in the first place. There was a mod in the custom pack I'm making which was causing issues with being able to even use the control's hitboxes at all, but in experimenting with disabling certain mods, I was able to get the controls working, but at the cost of the hitboxes moving...
The hitboxes only move upon right-clicking them. Left clicking the hitboxes works as it should with no issues.

### Minecraft version

1.19.2

### Mod Loader Platform type

Fabric

### Mod Loader version

0.14.14

### Tardis Refined version

Pre-release v0.1

### Other relevant versions

[Destination MC_test.zip](https://github.com/CommandrMoose/TardisRefined/files/10788289/Destination.MC_test.zip)

### Attach the relevant crash report file or log file: (Don't know how to find a crash report file? See the [Minecraft Wiki Tutorial](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)

https://pastebin.com/KG211NGG

**Comment by CommandrMoose** [comment]
Thanks for the report, and I appreciate you following our submission structure. However, with the information you've given us it's not possible to determine what might be causing it other than telling you its influenced by the logic of another mod. 

I can recommend attempting a [Split-Half Search](https://www.oreilly.com/library/view/apple-training-series/0321335465/0321335465_ch03lev1sec3.html) with your installed mods to find the mod that would be doing this. If one of the mods you've got listed influences entities in anyway, that could also be a place to look.

I'm going to leave this issue open for now, as we'd love to know what you'd find so that we might be able to prevent or warn users about it in the future.

**Comment by Swift2337** [comment]
The mod that appeared to be causing a separate, but arguably more pressing issue is the Advanced Genetics mod, which prevents the console controls from being right clicked at all in the first place. 
There appeared to be separate stability issues with a combination of mods in the pack I had, so I was unable to find the mod responsible for the above behavior, but I can at the very least tell you about the mod responsible for the original issue I was solving before I found the hitboxes were moving.

This is the Advanced Genetics mod:
https://www.curseforge.com/minecraft/mc-mods/advanced-genetics

**Comment by CommandrMoose** [comment]
We haven't heard from you in a while. Please let us know if this issue still persists for you and open this ticket back up :)
